[workspace]
default-members = ["msd-tool"]
members = ["msd-tool"]
resolver = "2"

[workspace.package]
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"
repository = "https://github.com/chenxiaolong/MSD"
publish = false
