on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Validate gradle wrapper checksum
        uses: gradle/actions/wrapper-validation@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

      - name: Set up JDK 21
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Install cargo-android
        shell: bash
        run: |
          cargo install \
              --git https://github.com/chenxiaolong/cargo-android \
              --tag v0.1.3

      - name: Install toolchains
        shell: bash
        run: |
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@f0deed1e0edfc6a9be95417288c0e1099b1eeec3 # v2.7.7

      # We currently use the old eagerly evaluated android.ndkDirectory value in
      # app/build.gradle.kts instead of the new lazily evaluated
      # androidComponents.sdkComponents.ndkDirectory because the latter doesn't
      # actually work (provider contains no value). However, because of this,
      # AGP's automatic NDK installation breaks, so we need to manually install
      # it here.
      - name: Install Android NDK
        shell: bash
        run: |
          set +o pipefail
          version=$(sed -nr -e 's/^\s*ndkVersion\s*=\s"(.+)".*$/\1/p' app/build.gradle.kts)
          yes | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "ndk;${version}"

      - name: Build and test
        # Debug build only since release builds require a signing key
        run: ./gradlew --no-daemon build zipDebug -x assembleRelease
