---
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Validate gradle wrapper checksum
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Install cargo-android
        shell: bash
        run: |
          cargo install \
              --git https://github.com/chenxiaolong/cargo-android \
              --tag v0.1.2

      - name: Install toolchains
        shell: bash
        run: |
          rustup target add aarch64-linux-android
          rustup target add x86_64-linux-android

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build and test
        # Debug build only since release builds require a signing key
        run: ./gradlew --no-daemon build zipDebug -x assembleRelease
